<a href="https://colab.research.google.com/github/iy627/programming/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
y = np.arange(10)

In [5]:
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a = np.array([1, 2, 3, 6])

In [7]:
b = np.linspace(0, 2, 4)

In [8]:
c = a - b

In [9]:
c

array([1.        , 1.33333333, 1.66666667, 4.        ])

In [10]:
a**2

array([ 1,  4,  9, 36])

In [11]:
a = np.linspace(-np.pi, np.pi, 100)

In [12]:
b = np.sin(a)

In [13]:
c = np.cos(a)

In [14]:
from numpy.random import rand

In [15]:
from numpy.linalg import solve, inv

In [16]:
a = np.array([[1, 2, 3], [3, 4, 6.7], [5, 9.0, 5]])

In [17]:
a.transpose()

array([[1. , 3. , 5. ],
       [2. , 4. , 9. ],
       [3. , 6.7, 5. ]])

In [18]:
inv(a)

array([[-2.27683616,  0.96045198,  0.07909605],
       [ 1.04519774, -0.56497175,  0.1299435 ],
       [ 0.39548023,  0.05649718, -0.11299435]])

In [19]:
b =  np.array([3, 2, 1])

In [20]:
solve(a, b)  # 解方程式 ax = b

array([-4.83050847,  2.13559322,  1.18644068])

In [21]:
c = rand(3, 3)

In [22]:
c

array([[0.91565201, 0.03476174, 0.67397613],
       [0.31045299, 0.94718707, 0.48776243],
       [0.81956908, 0.4142929 , 0.40685823]])

In [23]:
np.dot(a, c)

array([[ 3.99526523,  3.17201457,  2.87007566],
       [ 9.47988082,  6.66879591,  6.69892821],
       [11.47018232, 10.7699568 ,  9.79403361]])